name: Generate Stats SVG
on:
  schedule:
    - cron: '0 0 * * *' # Runs every night at midnight
  workflow_dispatch:     # Allows you to run it manually
jobs:
  generate-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate SVG
        uses: cicirello/user-statistician@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # This includes private repos automatically
          include-private: true 
          # Change 'dark' to 'light' if you prefer
          colors: dark
